Check for changes

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -11,4 +11,20 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Validate json files
-      run: npm run validate
+      run: npm run all
+
+    # This will fail the workflow if the `dist/` directory is different than
+    # expected.
+    - name: Compare Directories
+      id: diff
+      run: |
+        if [ ! -d dist/ ]; then
+          echo "Expected dist/ directory does not exist.  See status below:"
+          ls -la ./
+          exit 1
+        fi
+        if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
+          echo "Detected uncommitted changes after build. See status below:"
+          git diff --ignore-space-at-eol --text dist/
+          exit 1
+        fi
